.catalog:
  name: "MuddyMongoDB"
  version: "3.2-muddy2"
  description: "MongoDB Replica Set"
  uuid: muddymongo-0
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
    - variable: host_label
      label: "Host Label to MongoDB Tags"
      description: |
        Host label to use as MongoDB 'value' tag.
        Example: 'database'
      required: false
      type: "string"
mongo-cluster-node1:
  scale: 1
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name1}"
mongo-cluster-node2:
  scale: 1
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name2}"
mongo-cluster-node3:
  scale: 1
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name3}"
